### ISSUE TITLE
Wasm support (Rust)

### ISSUE THREAD

**Issue by Rauno56** [nearform/node-clinic-flame#105]
Using wasm breaks at analyzing step:

```
/path_to_node_modules/clinic/bin.js:539
        if (err) throw err
                 ^

Error: Encountered an unparseable frame "<alloc::vec::Vec<T> as core::ops::deref::Deref>::deref::h6e590f7df8989db3 [WASM:Opt]"
    at new FrameNode (/path_to_node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:71:15)
    at /path_to_node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:18:38
    at Array.map (<anonymous>)
    at new FrameNode (/path_to_node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:18:23)
    at /path_to_node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:18:38
    at Array.map (<anonymous>)
    at new FrameNode (/path_to_node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:18:23)
    at /path_to_node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:18:38
    at Array.map (<anonymous>)
    at new FrameNode (/path_to_node_modules/clinic/node_modules/@nearform/flame/analysis/frame-node.js:18:23)
```

Do you have any plans on this? I'm sure those frames can take all sorts of forms and shapes, but the structure for wasm frames should generally be the same.

I'd be happy to contribute with some guidance and support.

**Comment by jasnell** [comment]
support for WASM is planned for an upcoming release very soon

**Comment by area** [comment]
I tried using the `dev` branch and got past this error for me, but the file that is ultimately compiled does not show a flame graph and has errors in the console, the first of which is `Uncaught TypeError: accordion is not a function`. Is that expected with the dev branch, currently?

**Comment by goto-bus-stop** [comment]
@area Did you do `npm install` again after switching to the `dev` branch? the `accordion` variable is supposed to come from the [node-clinic-common](https://github.com/nearform/node-clinic-common) package, the main branch depends on an older version of it.

**Comment by area** [comment]
Ah, that was it. A rookie mistake! Sorry for the bother, it looks like it all works.
