### ISSUE TITLE
Button tooltip in wrong place

### ISSUE THREAD

**Issue by AlanSl** [nearform/node-clinic-flame#47]
The tooltip for the next and previous buttons is appearing on the flamegraph itself instead of next to the buttons:

![image](https://user-images.githubusercontent.com/29628323/48900962-cd5a3880-ee4b-11e8-8fc1-e381ed1135cc.png)

**Comment by AlanSl** [comment]
Fix in https://github.com/nearform/node-clinic-flame/pull/46

**Comment by mcollina** [comment]
Fix landed.
