### ISSUE TITLE
vertically center on load

### ISSUE THREAD

**Issue by mcollina** [nearform/node-clinic-flame#48]
I think we should vertically center on load, as the highlighted frame is not shown in the following diagram:

https://upload.clinicjs.org/public/45af5a28189fc3216bf64303acfda224bb0203223e1286df17010739f236073f/12320.clinic-flame.html

**Comment by cuginoAle** [comment]
That's weird, it seems to work fine for me. The chart scrolls the selected frame into view on page load.
Maybe you are referring to something else?

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/1298616/48936766-2ee1dc00-ef0c-11e8-8b80-b8ae6e0e2e5e.gif)

**Comment by mcollina** [comment]
You are right, let's close this.
