### ISSUE TITLE
No flame graph is visible in browser

### ISSUE THREAD

**Issue by adigarg** [nearform/node-clinic-flame#54]
Doctor and Bubbleprof both seem to work on the same repo, it's a simple example script creating a server and accessing mongodb but flame does not seem to generate any output and has the following errors in the console.

<img width="1641" alt="screen shot 2018-11-28 at 5 07 46 pm" src="https://user-images.githubusercontent.com/6471407/49192507-27696b00-f330-11e8-870d-bb37a45d2c19.png">

**Comment by mcollina** [comment]
Which Node version are you using? 
Can you post the example script, and how you are generating some load?

**Comment by AlanSl** [comment]
Hi @adigarg - if you still have the files from this broken profile, it'd be great if you could share them by running this command in the directory that the HTML file is in:

```
clinic upload 27911.clinic-flame
```

(substitute the number from the filename if it's different to the one in the screenshot)

I've just posted a PR that fixes all known causes of this particular error, but looking at your report, I suspect this one has a very different cause that we haven't encountered before.

**Comment by DylanC** [comment]
Closing since we have a fix merged in and we need more details to proceed.
