### ISSUE TITLE
Tile interaction

### ISSUE THREAD

**Issue by delvedor** [nearform/node-clinic-flame#86]
Hello! Thank you for this awesome project!

You can read this issue as a feature request or user feedback :)
In the previous version of flame (with the old UI), you could expand a tile of the graph just by click it, while now you must select the expand option from the dropdown.

How about restore the previous behavior and introduce a right click interaction that opens the dropdown?

**Comment by AlanSl** [comment]
Hi Delvedor, you can double-click to immediately expand, without needing to move the cursor onto the expand option.

We'll look at how to make this more intuitive. 

Did you try clicking then clicking again?
