### ISSUE TITLE
ctrl-c not working on Linux

### ISSUE THREAD

**Issue by mcollina** [nearform/node-clinic-flame#91]
If I'm running https://github.com/fastify/fastify-jitson/pull/2/files#diff-191e0b7edb58302b1f664f32b96a9513 with flame and hit ctrl-c, the process exits abruptly and nothing gets generated.

**Comment by mrister** [comment]
@mcollina I tried this and yet on a Mac the process seems to hang on crtl-c this is probably not expected? (another crl-c is needed to fully exit). I get the same thing on Ubuntu 18 VM by running 
clinic flame --on-port 'autocannon localhost:$PORT' -- node example/jitson.js

is this what you were referring to?

**Comment by goto-bus-stop** [comment]
I do also get the abrupt stop behaviour on Arch Linux. On Ctrl+C, it instantly exits. The `process.on('SIGINT')` and `process.on('SIGTERM')` handlers don't even fire. With Node 8.8, everything works as expected, but any later version I tried does not…

**Comment by goto-bus-stop** [comment]
in `clinic@4.0.3` it should work again!
