### ISSUE TITLE
Add support for Node v12.0

### ISSUE THREAD

**Issue by pbadenski** [nearform/node-clinic-flame#97]

**Comment by goto-bus-stop** [comment]
Are you running into problems on Node 12? CI suggests it should work: https://github.com/nearform/node-clinic-flame/pull/96

**Comment by pbadenski** [comment]
That's interesting.. sorry should've provided more details, I thought this was a well-known but untracked issue.

I'm surprised because I get yelled at by npm during installation because: https://github.com/nearform/node-clinic-flame/blob/master/package.json#L5

**Comment by goto-bus-stop** [comment]
Ahh gotcha! I'll add ^12 to it in the linked PR. Thanks for raising this :)
